[sources.allow-org]
github = [
    "mintlayer", # allow any code from mintlayer's github
]

[licenses]
# we reject code without a license
confidence-threshold = 0.92
allow = [
    "0BSD",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "ISC",
    "LicenseRef-ring",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Unlicense", # this is a specific license rather than no license at all
    "Zlib",
] # deny a license not in this set of licenses

[[licenses.clarify]]
name = "ring"
expression = "LicenseRef-ring"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[[licenses.clarify]]
name = "webpki"
expression = "LicenseRef-webpki"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[advisories]
version = 2
db-path = "~/.cargo/advisory-dbs"
db-urls = [ "https://github.com/RustSec/advisory-db" ]
yanked = "warn"
ignore = []
