[package]
name = "rpc-description"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]

rpc-description-macro = { path = "../description-macro" }

serde_json.workspace = true
