[package]
name = "rpc"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
test-support = []

[dependencies]
crypto = { path = "../crypto/" }
logging = { path = "../logging" }
randomness = { path = "../randomness" }
rpc-description = { path = "description" }
rpc-description-macro = { path = "description-macro" }
rpc-types = { path = "types" }
subsystem = { path = "../subsystem" }
utils = { path = "../utils/" }
utils-networking = { path = "../utils/networking" }

anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
jsonrpsee = { workspace = true, features = ["server", "server-core", "http-client", "ws-client", "macros"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tower = { workspace = true, features = ["util"] }

# This we keep here, and not in the workspace, because it comes from jsonrpsee and requires an older version
tower-http = { version = "0.4", features = ["auth", "set-header"] }
http = "0.2"
hyper = "0.14"

[dev-dependencies]
test-utils = { path = "../test-utils" }

expect-test.workspace = true
rstest.workspace = true
tokio.workspace = true
