[package]
name = "log_error"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
derive_more.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[dev-dependencies]
logging = { path = "../../logging" }
utils = { path = "../../utils" }

tracing.workspace = true
