[package]
name = "p2p-types"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]

common = { path = "../../common" }
rpc-description = { path = "../../rpc/description" }
serialization = { path = "../../serialization" }

parity-scale-codec.workspace = true
serde.workspace = true

[dev-dependencies]
