[package]
name = "storage-lmdb"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
logging = { path = '../../logging' }
storage-core = { path = '../core' }
utils = { path = '../../utils' }

lmdb-mintlayer = { git = 'https://github.com/mintlayer/lmdb-rs-mintlayer.git', tag = 'v0.16.2' }

[dev-dependencies]
rstest.workspace = true
storage-backend-test-suite = { path = "../backend-test-suite" }
tempfile.workspace = true
test-utils = { path = "../../test-utils" }

[[test]]
name = "backend"
harness = false
