[package]
name = "serialization-tagged-derive"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
itertools.workspace = true
proc-macro2 = "1.0"
